apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEKX//////////wEaDCVcs+HB08SSQflioyLVAeouvj6EOOEwvtJNmho9ERTSkj+qE0hb139KeaLj01zsYqQoh/I5phDARykyppVBJp9mTeIZ4t6YW4fjGX2ZQ94U5TkkqJhmr+v5ryFN/pfkQ6qZKH/nXdI3YR0e334BC8UlkKq34aecFb2zVphLJELsSLUhP0mCxY6azYU4L3657wdPkP8UyZliSoNRTrTDYPRDqEtIrGx/W0m8tRZoL6aKR9zjZRddX0kAV0fSOYo0/YZZL3ODnIVOqfzazLfS5QhqICPQjFDxPdi1wHR3qB8IVbxsOSiP0YipBjItYyRDZAgb+xWJ25EwhliZ/Cj+Z6OSnmDyE2c1JkY/p2YIFRV/BzWadKPi87Dh