apiVersion: v1
kind: Service
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: api-user
