apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    app: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend
