apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    app: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: reverseproxy
